---
- hosts: all

  vars:
    ansible_winrm_server_cert_validation: ignore
    pdc_administrator_password: "{{ ansible_password }}"

  tasks:
    - name: Print ansible_password
      ansible.builtin.debug:
        msg: "{{ ansible_password }}"

    - name: Print pdc_administrator_password
      ansible.builtin.debug:
        msg: "{{ pdc_administrator_password }}"

    - name: Install Active Directory
      ansible.windows.win_feature:
          name: AD-Domain-Services
          include_management_tools: yes
          include_sub_features: yes
          state: present
      register: install_ad_domain_services

    - name: Reboot if installing AD-Domain-Services feature requires it
      ansible.windows.win_reboot:
      when: install_ad_domain_services.reboot_required
      register: win_reboot

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        sleep: 5
        delay: 30
        timeout: 300
      when: win_reboot is changed

    - name: Create Domain
      ansible.windows.win_domain:
        dns_domain_name: 'demo.lab'
        safe_mode_password: '{{ ansible_password }}'
      register: create_domain

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        sleep: 5
        delay: 30
        timeout: 300
      when: create_domain is changed

    - name: Add Terminal Server License Servers to Network Service
      vars:
        ansible_user: DEMO\Administrator
      ansible.windows.win_shell: |
        net localgroup "Terminal Server License Servers" /Add 'Network Service'

    - name: Set Licensing Mode
      vars:
        ansible_user: DEMO\Administrator
      ansible.windows.win_shell: |
        New-ItemProperty `
        -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' `
        -Name 'LicensingMode' `
        -Value 4 `
        -PropertyType 'DWord'

    - name: Set License Servers
      vars:
        ansible_user: DEMO\Administrator
      ansible.windows.win_shell: |
        New-ItemProperty `
        -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' `
        -Name 'LicenseServers' `
        -Value 'localhost' `
        -PropertyType 'String'

    - name: Enable Remote Desktop Connections
      vars:
        ansible_user: DEMO\Administrator
      ansible.windows.win_shell: |
        Set-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 00000000 -UseTransaction
        Set-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" -Name "fSingleSessionPerUser" -Value 00000000 -UseTransaction
        Set-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 00000000 -UseTransaction

    - name: Install Remote Desktop Session Host with sub features
      vars:
        ansible_user: DEMO\Administrator
      ansible.windows.win_feature:
        name: RDS-RD-Server
        state: present
        include_sub_features: yes
      register: install_remote_desktop_services

    - name: Reboot if installing RDS-RD-Server feature requires it
      vars:
        ansible_user: DEMO\Administrator
      ansible.windows.win_reboot:
      when: install_remote_desktop_services.reboot_required
      register: win_reboot

    - name: Wait for the reboot to complete if there was a change.
      vars:
        ansible_user: DEMO\Administrator
      wait_for_connection:
        sleep: 5
        delay: 30
        timeout: 300
      when: win_reboot is changed
