---
- hosts: all
  vars:
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Install all security and critical updates without a scheduled task
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
